# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import FlyDB.client_grpc.db_pb2 as lib_dot_proto_dot_gstring_dot_db__pb2

class GStringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A client_grpc.Channel.
        """
        self.NewFlyDBService = channel.unary_unary(
                '/gstring.GStringService/NewFlyDBService',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.FlyDBOption.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.NewFlyDBResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/gstring.GStringService/Get',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetResponse.FromString,
                )
        self.Put = channel.unary_unary(
                '/gstring.GStringService/Put',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.SetRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.SetResponse.FromString,
                )
        self.Del = channel.unary_unary(
                '/gstring.GStringService/Del',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DelRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DelResponse.FromString,
                )
        self.Type = channel.unary_unary(
                '/gstring.GStringService/Type',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.TypeRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.TypeResponse.FromString,
                )
        self.StrLen = channel.unary_unary(
                '/gstring.GStringService/StrLen',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.StrLenRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.StrLenResponse.FromString,
                )
        self.GetSet = channel.unary_unary(
                '/gstring.GStringService/GetSet',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetSetRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetSetResponse.FromString,
                )
        self.Append = channel.unary_unary(
                '/gstring.GStringService/Append',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.AppendRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.AppendResponse.FromString,
                )
        self.Incr = channel.unary_unary(
                '/gstring.GStringService/Incr',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrResponse.FromString,
                )
        self.IncrBy = channel.unary_unary(
                '/gstring.GStringService/IncrBy',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByResponse.FromString,
                )
        self.IncrByFloat = channel.unary_unary(
                '/gstring.GStringService/IncrByFloat',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatResponse.FromString,
                )
        self.Decr = channel.unary_unary(
                '/gstring.GStringService/Decr',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrResponse.FromString,
                )
        self.DecrBy = channel.unary_unary(
                '/gstring.GStringService/DecrBy',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrByRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrByResponse.FromString,
                )
        self.Exists = channel.unary_unary(
                '/gstring.GStringService/Exists',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExistsRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExistsResponse.FromString,
                )
        self.Expire = channel.unary_unary(
                '/gstring.GStringService/Expire',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExpireRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExpireResponse.FromString,
                )
        self.Persist = channel.unary_unary(
                '/gstring.GStringService/Persist',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.PersistRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.PersistResponse.FromString,
                )
        self.MGet = channel.unary_unary(
                '/gstring.GStringService/MGet',
                request_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.MGetRequest.SerializeToString,
                response_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.MGetResponse.FromString,
                )


class GStringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewFlyDBService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Del(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Type(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StrLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Incr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrByFloat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Expire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Persist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GStringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewFlyDBService': grpc.unary_unary_rpc_method_handler(
                    servicer.NewFlyDBService,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.FlyDBOption.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.NewFlyDBResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.SetRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.SetResponse.SerializeToString,
            ),
            'Del': grpc.unary_unary_rpc_method_handler(
                    servicer.Del,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DelRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DelResponse.SerializeToString,
            ),
            'Type': grpc.unary_unary_rpc_method_handler(
                    servicer.Type,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.TypeRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.TypeResponse.SerializeToString,
            ),
            'StrLen': grpc.unary_unary_rpc_method_handler(
                    servicer.StrLen,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.StrLenRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.StrLenResponse.SerializeToString,
            ),
            'GetSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSet,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetSetRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.GetSetResponse.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.AppendRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.AppendResponse.SerializeToString,
            ),
            'Incr': grpc.unary_unary_rpc_method_handler(
                    servicer.Incr,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrResponse.SerializeToString,
            ),
            'IncrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrBy,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByResponse.SerializeToString,
            ),
            'IncrByFloat': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrByFloat,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatResponse.SerializeToString,
            ),
            'Decr': grpc.unary_unary_rpc_method_handler(
                    servicer.Decr,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrResponse.SerializeToString,
            ),
            'DecrBy': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrBy,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrByRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.DecrByResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExistsRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExistsResponse.SerializeToString,
            ),
            'Expire': grpc.unary_unary_rpc_method_handler(
                    servicer.Expire,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExpireRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.ExpireResponse.SerializeToString,
            ),
            'Persist': grpc.unary_unary_rpc_method_handler(
                    servicer.Persist,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.PersistRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.PersistResponse.SerializeToString,
            ),
            'MGet': grpc.unary_unary_rpc_method_handler(
                    servicer.MGet,
                    request_deserializer=lib_dot_proto_dot_gstring_dot_db__pb2.MGetRequest.FromString,
                    response_serializer=lib_dot_proto_dot_gstring_dot_db__pb2.MGetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gstring.GStringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GStringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewFlyDBService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/NewFlyDBService',
            lib_dot_proto_dot_gstring_dot_db__pb2.FlyDBOption.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.NewFlyDBResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Get',
            lib_dot_proto_dot_gstring_dot_db__pb2.GetRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Put',
            lib_dot_proto_dot_gstring_dot_db__pb2.SetRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.SetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Del(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Del',
            lib_dot_proto_dot_gstring_dot_db__pb2.DelRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.DelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Type',
            lib_dot_proto_dot_gstring_dot_db__pb2.TypeRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.TypeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StrLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/StrLen',
            lib_dot_proto_dot_gstring_dot_db__pb2.StrLenRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.StrLenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/GetSet',
            lib_dot_proto_dot_gstring_dot_db__pb2.GetSetRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.GetSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Append',
            lib_dot_proto_dot_gstring_dot_db__pb2.AppendRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.AppendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Incr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Incr',
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/IncrBy',
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrByRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrByResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncrByFloat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/IncrByFloat',
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.IncrByFloatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Decr',
            lib_dot_proto_dot_gstring_dot_db__pb2.DecrRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.DecrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecrBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/DecrBy',
            lib_dot_proto_dot_gstring_dot_db__pb2.DecrByRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.DecrByResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Exists',
            lib_dot_proto_dot_gstring_dot_db__pb2.ExistsRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.ExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Expire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Expire',
            lib_dot_proto_dot_gstring_dot_db__pb2.ExpireRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.ExpireResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Persist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/Persist',
            lib_dot_proto_dot_gstring_dot_db__pb2.PersistRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.PersistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gstring.GStringService/MGet',
            lib_dot_proto_dot_gstring_dot_db__pb2.MGetRequest.SerializeToString,
            lib_dot_proto_dot_gstring_dot_db__pb2.MGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
